// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.6
// source: trains.proto

package __

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddTrainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainNumber      string            `protobuf:"bytes,1,opt,name=TrainNumber,proto3" json:"TrainNumber,omitempty"`
	DepartureStation string            `protobuf:"bytes,2,opt,name=DepartureStation,proto3" json:"DepartureStation,omitempty"`
	ArrivalStation   string            `protobuf:"bytes,3,opt,name=ArrivalStation,proto3" json:"ArrivalStation,omitempty"`
	DepartureTime    string            `protobuf:"bytes,4,opt,name=DepartureTime,proto3" json:"DepartureTime,omitempty"`
	ArrivalTime      string            `protobuf:"bytes,5,opt,name=ArrivalTime,proto3" json:"ArrivalTime,omitempty"`
	Seats            []*SeatTypeAndNum `protobuf:"bytes,6,rep,name=Seats,proto3" json:"Seats,omitempty"`
}

func (x *AddTrainReq) Reset() {
	*x = AddTrainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainReq) ProtoMessage() {}

func (x *AddTrainReq) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainReq.ProtoReflect.Descriptor instead.
func (*AddTrainReq) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{0}
}

func (x *AddTrainReq) GetTrainNumber() string {
	if x != nil {
		return x.TrainNumber
	}
	return ""
}

func (x *AddTrainReq) GetDepartureStation() string {
	if x != nil {
		return x.DepartureStation
	}
	return ""
}

func (x *AddTrainReq) GetArrivalStation() string {
	if x != nil {
		return x.ArrivalStation
	}
	return ""
}

func (x *AddTrainReq) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *AddTrainReq) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *AddTrainReq) GetSeats() []*SeatTypeAndNum {
	if x != nil {
		return x.Seats
	}
	return nil
}

type SeatTypeAndNum struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SeatType string `protobuf:"bytes,1,opt,name=SeatType,proto3" json:"SeatType,omitempty"`
	SeatNum  int64  `protobuf:"varint,2,opt,name=SeatNum,proto3" json:"SeatNum,omitempty"`
}

func (x *SeatTypeAndNum) Reset() {
	*x = SeatTypeAndNum{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SeatTypeAndNum) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SeatTypeAndNum) ProtoMessage() {}

func (x *SeatTypeAndNum) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SeatTypeAndNum.ProtoReflect.Descriptor instead.
func (*SeatTypeAndNum) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{1}
}

func (x *SeatTypeAndNum) GetSeatType() string {
	if x != nil {
		return x.SeatType
	}
	return ""
}

func (x *SeatTypeAndNum) GetSeatNum() int64 {
	if x != nil {
		return x.SeatNum
	}
	return 0
}

type AddTrainResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *AddTrainResp) Reset() {
	*x = AddTrainResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddTrainResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddTrainResp) ProtoMessage() {}

func (x *AddTrainResp) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddTrainResp.ProtoReflect.Descriptor instead.
func (*AddTrainResp) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{2}
}

func (x *AddTrainResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateTrainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId          int64             `protobuf:"varint,1,opt,name=TrainId,proto3" json:"TrainId,omitempty"`
	TrainNumber      string            `protobuf:"bytes,2,opt,name=TrainNumber,proto3" json:"TrainNumber,omitempty"`
	DepartureStation string            `protobuf:"bytes,3,opt,name=DepartureStation,proto3" json:"DepartureStation,omitempty"`
	ArrivalStation   string            `protobuf:"bytes,4,opt,name=ArrivalStation,proto3" json:"ArrivalStation,omitempty"`
	DepartureTime    string            `protobuf:"bytes,5,opt,name=DepartureTime,proto3" json:"DepartureTime,omitempty"`
	ArrivalTime      string            `protobuf:"bytes,6,opt,name=ArrivalTime,proto3" json:"ArrivalTime,omitempty"`
	Seats            []*SeatTypeAndNum `protobuf:"bytes,7,rep,name=Seats,proto3" json:"Seats,omitempty"`
}

func (x *UpdateTrainReq) Reset() {
	*x = UpdateTrainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainReq) ProtoMessage() {}

func (x *UpdateTrainReq) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainReq.ProtoReflect.Descriptor instead.
func (*UpdateTrainReq) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateTrainReq) GetTrainId() int64 {
	if x != nil {
		return x.TrainId
	}
	return 0
}

func (x *UpdateTrainReq) GetTrainNumber() string {
	if x != nil {
		return x.TrainNumber
	}
	return ""
}

func (x *UpdateTrainReq) GetDepartureStation() string {
	if x != nil {
		return x.DepartureStation
	}
	return ""
}

func (x *UpdateTrainReq) GetArrivalStation() string {
	if x != nil {
		return x.ArrivalStation
	}
	return ""
}

func (x *UpdateTrainReq) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *UpdateTrainReq) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *UpdateTrainReq) GetSeats() []*SeatTypeAndNum {
	if x != nil {
		return x.Seats
	}
	return nil
}

type UpdateTrainResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *UpdateTrainResp) Reset() {
	*x = UpdateTrainResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTrainResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTrainResp) ProtoMessage() {}

func (x *UpdateTrainResp) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTrainResp.ProtoReflect.Descriptor instead.
func (*UpdateTrainResp) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateTrainResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTrainDetailReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *GetTrainDetailReq) Reset() {
	*x = GetTrainDetailReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrainDetailReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainDetailReq) ProtoMessage() {}

func (x *GetTrainDetailReq) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainDetailReq.ProtoReflect.Descriptor instead.
func (*GetTrainDetailReq) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{5}
}

func (x *GetTrainDetailReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetTrainDetailResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId          int64  `protobuf:"varint,1,opt,name=TrainId,proto3" json:"TrainId,omitempty"`
	TrainNumber      string `protobuf:"bytes,2,opt,name=TrainNumber,proto3" json:"TrainNumber,omitempty"`
	DepartureStation string `protobuf:"bytes,3,opt,name=DepartureStation,proto3" json:"DepartureStation,omitempty"`
	ArrivalStation   string `protobuf:"bytes,4,opt,name=ArrivalStation,proto3" json:"ArrivalStation,omitempty"`
	DepartureTime    string `protobuf:"bytes,5,opt,name=DepartureTime,proto3" json:"DepartureTime,omitempty"`
	ArrivalTime      string `protobuf:"bytes,6,opt,name=ArrivalTime,proto3" json:"ArrivalTime,omitempty"`
	TotalSeat        int64  `protobuf:"varint,7,opt,name=TotalSeat,proto3" json:"TotalSeat,omitempty"`
	CreateTime       string `protobuf:"bytes,8,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UpdateTime       string `protobuf:"bytes,9,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
}

func (x *GetTrainDetailResp) Reset() {
	*x = GetTrainDetailResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTrainDetailResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrainDetailResp) ProtoMessage() {}

func (x *GetTrainDetailResp) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrainDetailResp.ProtoReflect.Descriptor instead.
func (*GetTrainDetailResp) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{6}
}

func (x *GetTrainDetailResp) GetTrainId() int64 {
	if x != nil {
		return x.TrainId
	}
	return 0
}

func (x *GetTrainDetailResp) GetTrainNumber() string {
	if x != nil {
		return x.TrainNumber
	}
	return ""
}

func (x *GetTrainDetailResp) GetDepartureStation() string {
	if x != nil {
		return x.DepartureStation
	}
	return ""
}

func (x *GetTrainDetailResp) GetArrivalStation() string {
	if x != nil {
		return x.ArrivalStation
	}
	return ""
}

func (x *GetTrainDetailResp) GetDepartureTime() string {
	if x != nil {
		return x.DepartureTime
	}
	return ""
}

func (x *GetTrainDetailResp) GetArrivalTime() string {
	if x != nil {
		return x.ArrivalTime
	}
	return ""
}

func (x *GetTrainDetailResp) GetTotalSeat() int64 {
	if x != nil {
		return x.TotalSeat
	}
	return 0
}

func (x *GetTrainDetailResp) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

func (x *GetTrainDetailResp) GetUpdateTime() string {
	if x != nil {
		return x.UpdateTime
	}
	return ""
}

type DelTrainReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TrainId int64 `protobuf:"varint,1,opt,name=TrainId,proto3" json:"TrainId,omitempty"`
}

func (x *DelTrainReq) Reset() {
	*x = DelTrainReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTrainReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTrainReq) ProtoMessage() {}

func (x *DelTrainReq) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTrainReq.ProtoReflect.Descriptor instead.
func (*DelTrainReq) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{7}
}

func (x *DelTrainReq) GetTrainId() int64 {
	if x != nil {
		return x.TrainId
	}
	return 0
}

type DelTrainResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Success int64 `protobuf:"varint,1,opt,name=Success,proto3" json:"Success,omitempty"`
}

func (x *DelTrainResp) Reset() {
	*x = DelTrainResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_trains_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelTrainResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelTrainResp) ProtoMessage() {}

func (x *DelTrainResp) ProtoReflect() protoreflect.Message {
	mi := &file_trains_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelTrainResp.ProtoReflect.Descriptor instead.
func (*DelTrainResp) Descriptor() ([]byte, []int) {
	return file_trains_proto_rawDescGZIP(), []int{8}
}

func (x *DelTrainResp) GetSuccess() int64 {
	if x != nil {
		return x.Success
	}
	return 0
}

var File_trains_proto protoreflect.FileDescriptor

var file_trains_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x72, 0x61, 0x69, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xf2,
	0x01, 0x0a, 0x0b, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x20,
	0x0a, 0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x12, 0x2a, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e,
	0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x44, 0x65, 0x70,
	0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x72,
	0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x05,
	0x53, 0x65, 0x61, 0x74, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x41, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x05, 0x53, 0x65,
	0x61, 0x74, 0x73, 0x22, 0x46, 0x0a, 0x0e, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x41,
	0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x12, 0x1a, 0x0a, 0x08, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x53, 0x65, 0x61, 0x74, 0x4e, 0x75, 0x6d, 0x22, 0x1e, 0x0a, 0x0c, 0x41,
	0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0x8f, 0x02, 0x0a, 0x0e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x12, 0x18,
	0x0a, 0x07, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x07, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x69,
	0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x65,
	0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61,
	0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24,
	0x0a, 0x0d, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x72, 0x72, 0x69, 0x76,
	0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x53, 0x65, 0x61, 0x74, 0x73, 0x18,
	0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x53, 0x65, 0x61, 0x74, 0x54, 0x79, 0x70, 0x65,
	0x41, 0x6e, 0x64, 0x4e, 0x75, 0x6d, 0x52, 0x05, 0x53, 0x65, 0x61, 0x74, 0x73, 0x22, 0x21, 0x0a,
	0x0f, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64,
	0x22, 0x23, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61,
	0x69, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0xca, 0x02, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07,
	0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x54,
	0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x20, 0x0a, 0x0b, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x4e,
	0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x44, 0x65, 0x70, 0x61,
	0x72, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x10, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x26, 0x0a, 0x0e, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x53,
	0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e, 0x41, 0x72,
	0x72, 0x69, 0x76, 0x61, 0x6c, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d,
	0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x44, 0x65, 0x70, 0x61, 0x72, 0x74, 0x75, 0x72, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c, 0x54, 0x69, 0x6d,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x41, 0x72, 0x72, 0x69, 0x76, 0x61, 0x6c,
	0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x65, 0x61,
	0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x53, 0x65,
	0x61, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69,
	0x6d, 0x65, 0x22, 0x27, 0x0a, 0x0b, 0x44, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x18, 0x0a, 0x07, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x28, 0x0a, 0x0c, 0x44,
	0x65, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x18, 0x0a, 0x07, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x53, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x32, 0xc8, 0x01, 0x0a, 0x0c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x08, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61,
	0x69, 0x6e, 0x12, 0x0c, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x0d, 0x2e, 0x41, 0x64, 0x64, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x2b, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0f, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x39, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x12,
	0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x52,
	0x65, 0x71, 0x1a, 0x13, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x44, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x54, 0x72,
	0x61, 0x69, 0x6e, 0x12, 0x0c, 0x2e, 0x44, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65,
	0x71, 0x1a, 0x0d, 0x2e, 0x44, 0x65, 0x6c, 0x54, 0x72, 0x61, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x04, 0x5a, 0x02, 0x2e, 0x2f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_trains_proto_rawDescOnce sync.Once
	file_trains_proto_rawDescData = file_trains_proto_rawDesc
)

func file_trains_proto_rawDescGZIP() []byte {
	file_trains_proto_rawDescOnce.Do(func() {
		file_trains_proto_rawDescData = protoimpl.X.CompressGZIP(file_trains_proto_rawDescData)
	})
	return file_trains_proto_rawDescData
}

var file_trains_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_trains_proto_goTypes = []interface{}{
	(*AddTrainReq)(nil),        // 0: AddTrainReq
	(*SeatTypeAndNum)(nil),     // 1: SeatTypeAndNum
	(*AddTrainResp)(nil),       // 2: AddTrainResp
	(*UpdateTrainReq)(nil),     // 3: UpdateTrainReq
	(*UpdateTrainResp)(nil),    // 4: UpdateTrainResp
	(*GetTrainDetailReq)(nil),  // 5: GetTrainDetailReq
	(*GetTrainDetailResp)(nil), // 6: GetTrainDetailResp
	(*DelTrainReq)(nil),        // 7: DelTrainReq
	(*DelTrainResp)(nil),       // 8: DelTrainResp
}
var file_trains_proto_depIdxs = []int32{
	1, // 0: AddTrainReq.Seats:type_name -> SeatTypeAndNum
	1, // 1: UpdateTrainReq.Seats:type_name -> SeatTypeAndNum
	0, // 2: TrainService.AddTrain:input_type -> AddTrainReq
	3, // 3: TrainService.Update:input_type -> UpdateTrainReq
	5, // 4: TrainService.GetTrainDetail:input_type -> GetTrainDetailReq
	7, // 5: TrainService.DelTrain:input_type -> DelTrainReq
	2, // 6: TrainService.AddTrain:output_type -> AddTrainResp
	4, // 7: TrainService.Update:output_type -> UpdateTrainResp
	6, // 8: TrainService.GetTrainDetail:output_type -> GetTrainDetailResp
	8, // 9: TrainService.DelTrain:output_type -> DelTrainResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_trains_proto_init() }
func file_trains_proto_init() {
	if File_trains_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_trains_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trains_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SeatTypeAndNum); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trains_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddTrainResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trains_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trains_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTrainResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trains_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrainDetailReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trains_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTrainDetailResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trains_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTrainReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_trains_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelTrainResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_trains_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_trains_proto_goTypes,
		DependencyIndexes: file_trains_proto_depIdxs,
		MessageInfos:      file_trains_proto_msgTypes,
	}.Build()
	File_trains_proto = out.File
	file_trains_proto_rawDesc = nil
	file_trains_proto_goTypes = nil
	file_trains_proto_depIdxs = nil
}
